### ISSUE TITLE
其它项目问题

### ISSUE THREAD

**Issue by nsfoxer** [catsout/dotfiles#1]
抱歉，我发现flathub上由您维护的[NetEase Cloud Music GTK](https://flathub.org/zh-Hans/apps/com.github.gmg137.netease-cloud-music-gtk)需要更新为最新版本2.2.0。我无法找到您的邮件地址和其它联系方式，只好在这个无关的项目下提出此issue。

  相关isssue连接 #https://github.com/gmg137/netease-cloud-music-gtk/issues/246#issue-1848619311

![pic](https://user-images.githubusercontent.com/32675834/260309440-7da52192-1832-4d04-97d0-ca25da39809f.png)

**Comment by catsout** [comment]
pr welcome.
